POST http://localhost:8080/api/users/register
Content-Type: application/json

{
 "user": {
     "username": "haihihi1",
     "password": "hhsh0302",
     "phone_number": "222222222",
     "email_address": "ajdhashdsa"
 }
}

###
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
    "userAuth": {
        "username": "haihihi1",
        "password": "hhsh0302"
    }
}


###

GET http://localhost:8080/api/categories
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTYzMzJlNjExMjllNmM5NWQ2NTQ3NWEiLCJ1c2VybmFtZSI6ImhhaWhpaGkxIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE2MzM4OTEwNTYsImV4cCI6MTYzMzkwOTA1Nn0.k8VVO9GXLY4KoOFAjx9y9wy_21aPJ2fVmoDeMltYtb0 
###
