POST http://localhost:8080/api/users/register
Content-Type: application/json

{
 "user": {
     "username": "haihihi1",
     "password": "hhsh0302",
     "phone_number": "222222222",
     "email_address": "ajdhashdsa"
 }
}

###
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
     
        "username": "haihihi",
        "password": "hhsh0302"
    
}


###

GET http://localhost:8080/api/categories
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTYzMmI3YjRlMjNkMGE4OTAwNjU0NDMiLCJ1c2VybmFtZSI6ImhhaWhpaGkiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2MzQwMTk5MjYsImV4cCI6MTYzNDAzNzkyNn0.sHLwWFr1Sw1h9-Zw4jKVeUfwEFD9wJF17nDedBDI4k0 
###

POST http://localhost:8080/api/categories
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTYzMmI3YjRlMjNkMGE4OTAwNjU0NDMiLCJ1c2VybmFtZSI6ImhhaWhpaGkiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2MzQwMTk5MjYsImV4cCI6MTYzNDAzNzkyNn0.sHLwWFr1Sw1h9-Zw4jKVeUfwEFD9wJF17nDedBDI4k0 
Content-Type: application/json

{
    "category": {

    "name": "hihi",
    "cat_slug": "hihi"
    }
}


###

GET http://localhost:8080/api/products
Content-Type: application/json

{
    "query":{
         "cat_slug": "dau-xa-toc"
    }
}